site_name: ModernPIDControlSS Documentation
# Page tree
nav:
  - Home: index.md
  - About: about.md

# Theme Configuration
#theme: mkdocs
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs
    - instant
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
  favicon: assets/favicon.png

repo_name: ModernPIDControlSS
repo_url: https://github.com/somefunagba/ModernPIDControlSS